Update Glossario
italia/pianotriennale-ict-doc pull request #14
Opened 2017-06-01 15:24 UTC by bianchi74

- Urgent: "Polo Nazionale Strategico" modified. The current definition is obsolete. It has to be modified as suggested or, alternatively, removed.   
- "Conservazione Perenne" has to be removed. The definition is misleading.
- "CERT" modified. The proposed definition improves the current. In any case a typo has to be corrected ("incidenti" instead of "eventi").

2017-06-09 10:22 UTC, gvarisco commented on doc/appendici/glossario.rst
> +| Polo strategico nazionale                                                                                 | Insieme di infrastrutture Insieme di infrastrutture IT (centralizzate o distribuite), ad
Insieme di infrastrutture è ripetuto

2017-06-09 10:23 UTC, gvarisco requested changes
Insieme di infrastrutture è ripetuto

2017-06-09 10:27 UTC, gvarisco commented
@bianchi74 dai una occhiata alla review! Grazie! 👍

2017-06-13 16:03 UTC, bianchi74 commented
@gvarisco la ripetizione "Insieme di infrastrutture" era già stata rimossa (probabilmente da un altro contributor). Nel frattempo però ho visto che sono stati introdotti errori di formattazione della tabella contente il glossario che, probabilmente, hanno fatto fallire la build su readthedocs (relativamente alla pagina del glossario, attualmente vuota).

2017-06-13 16:06 UTC, bianchi74 commented
P.S. @gvarisco abbiamo verificato oggi con @rasky che, dopo gli ultimi commit, sphinx-build produce diversi warning. Potrebbe essere saltata qualche tabella anche nei capitoli. Grazie e a presto.

2017-06-13 23:49 UTC, merged